#!/bin/sh
#
# see: dh_installdeb(1)
#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

set -e

if [ "x$1" = "xconfigure" ]; then
    adduser --quiet --system --group --home /var/cache/yubikey-val --no-create-home --disabled-password --system yhsm-valsrv

    # yhsm-valsrv needs to be in the 'dialout' group to access /dev/ttyACM*
    adduser --quiet yhsm-valsrv dialout
fi

invoke-rc.d yhsm-validation-server restart

#DEBHELPER#
